# Generated by Django 5.2 on 2026-05-22 11:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('risk_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('road_condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=20)),
                ('drain_status', models.CharField(choices=[('clear', 'Clear'), ('partial', 'Partially Blocked'), ('blocked', 'Blocked')], default='clear', max_length=20)),
                ('pothole_count', models.IntegerField(default=0)),
                ('elevation_risk', models.CharField(choices=[('flat', 'Flat Terrain'), ('slight_slope', 'Slight Slope'), ('significant_slope', 'Significant Slope'), ('depression', 'Depression / Low-lying')], default='flat', max_length=30)),
                ('analysis_text', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(help_text='Latitude of the flood zone center')),
                ('lng', models.FloatField(help_text='Longitude of the flood zone center')),
                ('risk_level', models.IntegerField(default=0, help_text='Risk level from 0 (safe) to 100 (extreme danger)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_category', models.CharField(choices=[('green', 'Low Risk'), ('yellow', 'Moderate Risk'), ('red', 'High Risk')], default='green', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flood Zone',
                'verbose_name_plural': 'Flood Zones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('optimization_param', models.CharField(default='lowest_risk', help_text="Either 'lowest_risk' or 'shortest_path'", max_length=50)),
                ('route_data', models.JSONField(default=dict)),
                ('risk_score', models.FloatField(default=0.0)),
                ('duration_estimate', models.CharField(blank=True, default='', max_length=100)),
                ('distance_km', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route Query',
                'verbose_name_plural': 'Route Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='Unique sensor identifier e.g. SN-402', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('lat', models.FloatField(help_text='Latitude of sensor placement')),
                ('lng', models.FloatField(help_text='Longitude of sensor placement')),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sensor Node',
                'verbose_name_plural': 'Sensor Nodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Relative humidity percentage')),
                ('rainfall_mm', models.FloatField(default=0.0, help_text='Rainfall in millimeters')),
                ('wind_speed', models.FloatField(default=0.0, help_text='Wind speed in km/h')),
                ('condition', models.CharField(blank=True, default='', max_length=100)),
                ('forecast_json', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Informational')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='floodapi.floodzone')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='floodapi.sensornode')),
            ],
            options={
                'verbose_name': 'Flood Alert',
                'verbose_name_plural': 'Flood Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level_cm', models.FloatField(help_text='Water level in centimeters')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('rssi', models.IntegerField(blank=True, help_text='Signal strength indicator', null=True)),
                ('flow_rate', models.FloatField(blank=True, help_text='Water flow rate in L/min', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='floodapi.sensornode')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
